-- 코드를 입력하세요
# CAR_ID, CAR_TYPE, FEE

SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE*(100-DISCOUNT_RATE)*0.01*30) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING (CAR_TYPE)
WHERE (CAR_TYPE='세단' OR CAR_TYPE='SUV') 
    AND DURATION_TYPE='30일 이상' 
    AND CAR_ID NOT IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE (START_DATE < '2022-11-30' AND END_DATE > '2022-11-01')
    )
    AND (DAILY_FEE*(100-DISCOUNT_RATE)*0.01*30 >= 500000 AND DAILY_FEE*(100-DISCOUNT_RATE)*0.01*30 < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;