-- 코드를 입력하세요
-- SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE ON_S
-- WHERE TO_CHAR(SALES_DATE, 'YYYY-MM-DD') > '2022-02-28' AND TO_CHAR(SALES_DATE, 'YYYY-MM-DD') < '2022-04-01'

-- UNION

-- SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT FROM OFFLINE_SALE OFF_S
-- WHERE TO_CHAR(SALES_DATE, 'YYYY-MM-DD') > '2022-02-28' AND TO_CHAR(SALES_DATE, 'YYYY-MM-DD') < '2022-04-01'

-- ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
-- ;

SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE EXTRACT(month from SALES_DATE) = 03 AND EXTRACT(year from SALES_DATE) = 2022

UNION

SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE EXTRACT(month from SALES_DATE) = 03 AND EXTRACT(year from SALES_DATE) = 2022

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID