-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR USING (MEMBER_ID)
WHERE RR.MEMBER_ID IN (
    SELECT MEMBER_ID FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT COUNT(*) FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;

