-- 코드를 입력하세요
SELECT CAR_ID, MAX(IF (C.START_DATE > '2022-10-16' OR '2022-10-16' > C.END_DATE, '대여 가능', '대여중')) AS AVAILABLITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C ORDER BY CAR_ID DESC;

# WITH AVAIL_CARS AS(
#   SELECT CAR_ID 
#   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
#   WHERE START_DATE<='2022-10-16' AND END_DATE>='2022-10-16'
# )

# SELECT DISTINCT(CAR_ID), '대여중' AS AVAILABILITY FROM AVAIL_CARS 
# UNION
# SELECT DISTINCT(C.CAR_ID), '대여 가능' AS AVAILABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C WHERE C.CAR_ID NOT IN (SELECT CAR_ID FROM AVAIL_CARS) 
# ORDER BY CAR_ID DESC