-- 코드를 입력하세요
SELECT h.HISTORY_ID, 
    CASE 
        WHEN (h.END_DATE-h.START_DATE+1) >= 7 THEN ROUND(c.DAILY_FEE*(h.END_DATE-h.START_DATE+1)*(100-p.DISCOUNT_RATE)*0.01, 1)
        ELSE c.DAILY_FEE*(h.END_DATE-h.START_DATE+1)
    END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c 
    ON h.CAR_ID = c.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p 
    ON c.CAR_TYPE = p.CAR_TYPE 
    AND p.DURATION_TYPE = (
        CASE 
            WHEN (h.END_DATE-h.START_DATE+1) >= 90 THEN '90일 이상'
            WHEN (h.END_DATE-h.START_DATE+1) >= 30 THEN '30일 이상'
            WHEN (h.END_DATE-h.START_DATE+1) >= 7 THEN '7일 이상'
        END
    )
WHERE c.CAR_TYPE = '트럭' 
    
ORDER BY FEE DESC, h.HISTORY_ID DESC
;