-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT_NO, MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AP
JOIN PATIENT PT USING (PT_NO)
JOIN DOCTOR DR USING (MCDP_CD)
WHERE AP.MDDR_ID = DR.DR_ID
    AND APNT_CNCL_YN = 'N' 
    AND TO_CHAR(APNT_YMD, 'YYYY-MM-DD') = '2022-04-13' 
    AND MCDP_CD = 'CS'

ORDER BY APNT_YMD
;